### ISSUE TITLE
Update to ASP.NET Core 2.1.2

### ISSUE THREAD

**Issue by henkmollema** [GoogleCloudPlatform/aspnet-docker#100]
When will the ASP.NET Core Docker image be updated to the latest 2.1.2 patch?

cc @iantalarico

**Comment by iantalarico** [comment]
@henkmollema We are starting a release today.  Worst case will be out by tomorrow.

**Comment by henkmollema** [comment]
Perfect! Thank you.

**Comment by iantalarico** [comment]
See #101 Should be released soon the other 2.0 and 1.* releases are coming soon too.

**Comment by henkmollema** [comment]
@iantalarico when are  the images expected to be pushed to GCR?

**Comment by iantalarico** [comment]
@henkmollema: Hopefully today.  @sharifelgamal is doing the release this time.  

@sharifelgamal: do you have an eta on this release?

**Comment by sharifelgamal** [comment]
This is be done today.

**Comment by sharifelgamal** [comment]
This should be done.

**Comment by iantalarico** [comment]
@sharifelgamal Thanks!

**Comment by henkmollema** [comment]
Thanks @iantalarico and @sharifelgamal! 👍
