### ISSUE TITLE
ASP.NET Core 2.1.3

### ISSUE THREAD

**Issue by henkmollema** [GoogleCloudPlatform/aspnet-docker#108]
Here I am again 😄 

When will the Docker images with ASP.NET Core 2.1.3 runtime be available on GAE? Thanks in advance!

**Comment by iantalarico** [comment]
@sharifelgamal @dlorenc FYI

**Comment by henkmollema** [comment]
This was fixed by 04e618e8f466f9cf72bbf84ee7495a8d6abe4cff.
