### ISSUE TITLE
Update the runtime image to support .NET Core 1.1

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/aspnet-docker#21]
Update the image to support .NET Core 1.1.

**Comment by blackie1019** [comment]
@ivannaranjo , I would like to know that already has official runtime image for .NET Core 1.1 or we should create self container? Thanks for your reply!

**Comment by ivannaranjo** [comment]
We don't have yet an official 1.1 image, we're working on it. I hope we can get one out for you guys soon. What we have today is at gcr.io/google-appengine/aspnetcore:1.1, but it not officially supported.

**Comment by ivannaranjo** [comment]
The 1.1 support is now in, haven't done a broad announcement yet. The VS extension will complain about it, but the support will be in the next release.
