### ISSUE TITLE
Consider using the "versioning" tool in runtimes_common to generate versioned Dockerfiles/cloudbuilds.

### ISSUE THREAD

**Issue by dlorenc** [GoogleCloudPlatform/aspnet-docker#47]
The container marketplace team has developed these tools here:
https://github.com/GoogleCloudPlatform/runtimes-common/tree/master/versioning

Which they use to handle generating versioned cloudbuilds and Dockerfiles. These might allow you to avoid having to check them all in.

**Comment by ivannaranjo** [comment]
This is no longer applicable, we're creating a single cloudbuild.yaml per major version of the runtime that builds all supported runtimes and that runs structural and functional tests.
