### ISSUE TITLE
Add test image to verify the prepare_project.py script.

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/aspnet-docker#52]
We need to make sure that the script will succeed in creating Dockerfiles for all supported versions of the .NET Core runtime.

**Comment by SurferJeffAtGoogle** [comment]
+1

**Comment by ivannaranjo** [comment]
Working on adding full tests of the builder.

**Comment by ivannaranjo** [comment]
This was fixed with #61
