### ISSUE TITLE
ASP.NET Core 2.1 preview images

### ISSUE THREAD

**Issue by henkmollema** [GoogleCloudPlatform/aspnet-docker#89]
Will Google provide images for ASP.NET Core preview bits?

**Comment by henkmollema** [comment]
I could send a PR for this, but the 2.1 runtime would need to be uploaded to the storage bucket.

The cloud builder image would need an update as well.

**Comment by henkmollema** [comment]
Thanks Ian!

**Comment by iantalarico** [comment]
@henkmollema I misspoke (Sorry I've just taken over this project and still am figuring it out), we do not support preview images, but as soon as 2.1 is out of preview we will push a new image.

While not supported or official (or well documented) we do have a [staging registry](https://github.com/GoogleCloudPlatform/aspnet-docker/blob/0ff72504ead1bcc9160c9b04423dec5d6767883a/tools/test.sh#L46).  If you are deploying to GAE Flex you could use these images if you switch your `runtime` to `custom`

**Comment by henkmollema** [comment]
I see. I've pushed my own Docker image to the registry for now. Thanks @iantalarico.
